### ISSUE TITLE
Make obsolete the species selection

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pgatk#12]
@cschlaffner should we made obsolete in the code the species selection now that all ENSEML species are supported. ?

**Comment by cschlaffner** [comment]
@ypriverol  I have included that in the last pull request already. README was updated accordingly as well

**Comment by ypriverol** [comment]
Ok perfect. I need to remove it from my pipelines then. Are you available on skype? Would like to coordinate some things with you.
